### ISSUE TITLE
TestFlight expired

### ISSUE THREAD

**Issue by gregoryw3** [Cldfire/minecraft-status#12]
Not sure if this is appropriate for the issue tab, but wanted to let you know that the TestFlight has expired. 

Thank you for making this wonderful widget.

**Comment by Cldfire** [comment]
Definitely appropriate for the issues tab! 😄 Thanks for letting me know. I'm going to be traveling a bit over the next couple weeks but I'll see if I can find the time to get a new build out.

Glad you like the widget :) the plan was to release it on the app store a few months ago, but Apple rejected my submission for "not having enough content". I'm hoping to find the time to add some more stuff and re-submit before the end of the year.

**Comment by Cldfire** [comment]
Just a heads up, the testflight build will be expiring again soon and this time I will not be replacing it as I've sadly decided to bring this project to an end. See https://github.com/Cldfire/minecraft-status#note for why.

If you or anyone else would be interested in forking this and continuing development, please feel free! :)
