### ISSUE TITLE
Support bedrock servers

### ISSUE THREAD

**Issue by Cldfire** [Cldfire/minecraft-status#5]
The [mcping library](https://github.com/Scetch/mcping) currently doesn't support pinging bedrock servers. Once it does, it would be nice to add support for those to this app.

**Comment by Cldfire** [comment]
See https://github.com/Scetch/mcping/issues/6.

**Comment by Cldfire** [comment]
Branch is up with initial support: https://github.com/Scetch/mcping/tree/bedrock

**Comment by Cldfire** [comment]
`mcping` now supports pinging bedrock servers, just gotta make use of it in the app.

**Comment by ilyaleb99** [comment]
Awesome

**Comment by Cldfire** [comment]
Closed by #7.
